//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Clientes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysClientes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysClientes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datos.Clientes.QuerysClientes", typeof(QuerysClientes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Cliente set
        ///  
        ///  Nombre			  =@Nombre
        ///  ,Direccion			  =@Direccion
        ///  ,Correo			  =@Correo
        ///  ,Telefono            =@Telefono
        ///  ,Identificacion	  =@Identificacion
        ///  ,Tipo_Identificacion =@Tipo_Identificacion
        ///  where id = @id.
        /// </summary>
        internal static string ActualizarCliente {
            get {
                return ResourceManager.GetString("ActualizarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Cliente set borrado =1 where id = @id.
        /// </summary>
        internal static string BorrarCliente {
            get {
                return ResourceManager.GetString("BorrarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Nombre
        ///      ,Direccion
        ///      ,Correo
        ///      ,Telefono
        ///      ,Identificacion
        ///      ,Tipo_Identificacion
        ///  FROM Cliente where  Borrado=0.
        /// </summary>
        internal static string ConsultarClientes {
            get {
                return ResourceManager.GetString("ConsultarClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Cliente(
        ///       Nombre
        ///      ,Direccion
        ///      ,Correo
        ///      ,Telefono
        ///      ,Identificacion
        ///      ,Tipo_Identificacion
        ///      ,Borrado
        ///	  )values (
        ///       @Nombre
        ///      ,@Direccion
        ///      ,@Correo
        ///      ,@Telefono
        ///      ,@Identificacion
        ///      ,@Tipo_Identificacion
        ///	  ,0
        ///	  ).
        /// </summary>
        internal static string InsertarCliente {
            get {
                return ResourceManager.GetString("InsertarCliente", resourceCulture);
            }
        }
    }
}
