//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Empleados {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysEmpleados {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysEmpleados() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datos.Empleados.QuerysEmpleados", typeof(QuerysEmpleados).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update  dbo.Cargo set nombre =@nombre where id=@id.
        /// </summary>
        internal static string ActualizarCargo {
            get {
                return ResourceManager.GetString("ActualizarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Departamento set nombre=@nombre where id=@id.
        /// </summary>
        internal static string ActualizarDepartamento {
            get {
                return ResourceManager.GetString("ActualizarDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update empleado set
        ///	   Nombre =@Nombre
        ///      ,Cedula   =@Cedula
        ///      ,Correo =@Correo
        ///      ,Telefono  =@Telefono
        ///      ,Codigo_Empleado =@Codigo_Empleado
        ///      ,CargoID =@CargoID
        ///      ,DepartamentoID =@DepartamentoID
        ///WHERE id =@id.
        /// </summary>
        internal static string ActualizarEmpleado {
            get {
                return ResourceManager.GetString("ActualizarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update  dbo.Cargo set borrado =1 where id=@id.
        /// </summary>
        internal static string BorrarCargo {
            get {
                return ResourceManager.GetString("BorrarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Departamento set borrado=1 where id=@id.
        /// </summary>
        internal static string BorrarDepartamento {
            get {
                return ResourceManager.GetString("BorrarDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update empleado set borrado =1
        ///WHERE id =@id.
        /// </summary>
        internal static string BorrarEmpleado {
            get {
                return ResourceManager.GetString("BorrarEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Nombre
        ///  FROM dbo.Cargo where borrado =0.
        /// </summary>
        internal static string ConsultarCargos {
            get {
                return ResourceManager.GetString("ConsultarCargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Nombre
        ///  FROM dbo.Departamento where borrado =0.
        /// </summary>
        internal static string ConsultarDepartamaneto {
            get {
                return ResourceManager.GetString("ConsultarDepartamaneto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT e.ID
        ///      ,e.Nombre
        ///      ,Cedula
        ///      ,Correo
        ///      ,Telefono
        ///      ,Codigo_Empleado
        ///      ,e.CargoID
        ///      ,e.DepartamentoID
        ///      ,Fecha_Ingreso
        ///      ,Fecha_Nacimiento
        ///	  ,c.Nombre as Cargo
        ///	  ,d.Nombre as Departamento
        ///  FROM dbo.Empleado e
        ///  inner join Cargo c on e.CargoID=c.ID
        ///  inner join Departamento d on e.DepartamentoID=d.ID
        ///  where e.borrado =0.
        /// </summary>
        internal static string ConsultarEmpleados {
            get {
                return ResourceManager.GetString("ConsultarEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into dbo.Cargo (nombre, borrado) values(@nombre,0).
        /// </summary>
        internal static string InsertarCargo {
            get {
                return ResourceManager.GetString("InsertarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Departamento (nombre, borrado) values(@nombre, 0).
        /// </summary>
        internal static string InsertarDepartamento {
            get {
                return ResourceManager.GetString("InsertarDepartamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into empleado (
        ///	   Nombre
        ///      ,Cedula
        ///      ,Correo
        ///      ,Telefono
        ///      ,Codigo_Empleado
        ///      ,CargoID
        ///      ,DepartamentoID
        ///      ,Fecha_Ingreso
        ///      ,Fecha_Nacimiento
        ///	  ,Borrado
        ///	  )
        ///	  values
        ///	  (
        ///		@Nombre
        ///       ,@Cedula
        ///       ,@Correo
        ///       ,@Telefono
        ///       ,@Codigo_Empleado
        ///       ,@CargoID
        ///       ,@DepartamentoID
        ///       ,@Fecha_Ingreso
        ///       ,@Fecha_Nacimiento
        ///	   ,0
        ///	  ).
        /// </summary>
        internal static string InsertarEmpleado {
            get {
                return ResourceManager.GetString("InsertarEmpleado", resourceCulture);
            }
        }
    }
}
