//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Incidencias {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysIncidencias {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysIncidencias() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datos.Incidencias.QuerysIncidencias", typeof(QuerysIncidencias).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Incidencia set Descripcion=@Descripcion
        ///      ,TallerID = @TallerID
        ///      ,VehiculoID = @VehiculoID
        ///	  ,Completada = @Completada
        ///	  where id =@id.
        /// </summary>
        internal static string ActualizarIncidencia {
            get {
                return ResourceManager.GetString("ActualizarIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update vehiculo set Mantenimiento =0  where id =@id.
        /// </summary>
        internal static string ActualizarMatenimientoVehiculos {
            get {
                return ResourceManager.GetString("ActualizarMatenimientoVehiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update dbo.Taller set nombre = @nombre
        ///  ,Direccion = @direccion
        ///  ,telefono =@telefono
        ///  where id =@id.
        /// </summary>
        internal static string ActualizarTaller {
            get {
                return ResourceManager.GetString("ActualizarTaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Incidencia set Borrado = 1 where id = @id.
        /// </summary>
        internal static string BorrarIncidencia {
            get {
                return ResourceManager.GetString("BorrarIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update dbo.Taller set Borrado = 1 where id =@id.
        /// </summary>
        internal static string BorrarTaller {
            get {
                return ResourceManager.GetString("BorrarTaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.ID
        ///      ,Descripcion
        ///      ,Fecha_Entrada
        ///      ,Fecha_Salida
        ///      ,TallerID
        ///      ,VehiculoID
        ///      ,Completada
        ///	  ,t.Nombre as taller
        ///	  ,chasis +&apos; | &apos;+ placa as vehiculo
        ///  FROM dbo.Incidencia a
        ///  inner join Taller t on t.ID = a.TallerID
        ///  inner join Vehiculo v on v.ID = a.VehiculoID
        ///  where a.Borrado =0.
        /// </summary>
        internal static string ConsultarIncidencia {
            get {
                return ResourceManager.GetString("ConsultarIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Nombre
        ///      ,Direccion
        ///      ,Telefono
        ///  FROM dbo.Taller
        ///
        ///  where borrado =0.
        /// </summary>
        internal static string ConsultarTaller {
            get {
                return ResourceManager.GetString("ConsultarTaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ID, chasis +&apos; | &apos;+ placa as nombre from vehiculo where Mantenimiento = 1.
        /// </summary>
        internal static string ConsultarVehiculosMatenimientos {
            get {
                return ResourceManager.GetString("ConsultarVehiculosMatenimientos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Incidencia(
        ///	   Descripcion
        ///      ,Fecha_Entrada
        ///      ,Fecha_Salida
        ///      ,TallerID
        ///      ,VehiculoID
        ///      ,Completada
        ///	  ,Borrado
        ///	  )
        ///	  values(
        ///	   @Descripcion
        ///      ,@Fecha_Entrada
        ///      ,@Fecha_Salida
        ///      ,@TallerID
        ///      ,@VehiculoID
        ///      ,0
        ///	  ,0
        ///	  ).
        /// </summary>
        internal static string InsertarIncidencia {
            get {
                return ResourceManager.GetString("InsertarIncidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into taller (nombre,Direccion,Telefono,borrado)
        ///  values (@nombre,@Direccion,@Telefono,0).
        /// </summary>
        internal static string InsertarTaller {
            get {
                return ResourceManager.GetString("InsertarTaller", resourceCulture);
            }
        }
    }
}
