//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Entregas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuerysEntregas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuerysEntregas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Datos.Entregas.QuerysEntregas", typeof(QuerysEntregas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Prioridad set nombre =@nombre, horas =@horas where id = @id.
        /// </summary>
        internal static string ActualizarPrioridad {
            get {
                return ResourceManager.GetString("ActualizarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Entrega set
        ///       Destino= @Destino
        ///      ,Descripcion	=@Descripcion
        ///      ,Peso			=@Peso
        ///      ,EmpleadoID	=@EmpleadoID
        ///      ,ClienteID	=@ClienteID
        ///      ,PrioridadID	=@PrioridadID
        ///  
        ///
        ///  where id =@id.
        /// </summary>
        internal static string ActualziarEntrega {
            get {
                return ResourceManager.GetString("ActualziarEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Entrega set Borrado=1 where id =@id.
        /// </summary>
        internal static string BorrarEntrega {
            get {
                return ResourceManager.GetString("BorrarEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Prioridad set Borrado =1 where id = @id.
        /// </summary>
        internal static string BorrarPrioridad {
            get {
                return ResourceManager.GetString("BorrarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.ID
        ///      ,Destino
        ///      ,Fecha_Salida
        ///      ,Fecha_Regreso
        ///      ,Descripcion
        ///      ,Peso
        ///      ,EmpleadoID
        ///      ,ClienteID
        ///      ,PrioridadID
        ///      ,b.Nombre Empleado
        ///	  ,c.Nombre Cliente
        ///	  ,d.Nombre Prioridad
        ///  FROM Entrega a 
        ///  inner join Empleado b on a.EmpleadoID = b.ID
        ///  inner join Cliente c on a.ClienteID=c.ID
        ///  inner join Prioridad d on d.ID=a.PrioridadID
        ///  where a.Borrado =0.
        /// </summary>
        internal static string ConsultarEntrega {
            get {
                return ResourceManager.GetString("ConsultarEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ID
        ///      ,Nombre
        ///      ,Horas
        ///  FROM dbo.Prioridad where borrado =0.
        /// </summary>
        internal static string ConsultarPrioridad {
            get {
                return ResourceManager.GetString("ConsultarPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select b.id, b.Nombre from  Vehiculo a
        ///inner join Empleado b on b.ID= a.EmpleadoID
        ///left join Entrega e on b.Id=e.ID and e.borrado =0
        ///
        ///where a.Borrado=0 and Mantenimiento=0.
        /// </summary>
        internal static string ConsultarVehiculosEmpleadosDisponibles {
            get {
                return ResourceManager.GetString("ConsultarVehiculosEmpleadosDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into entrega (
        ///      Destino
        ///      ,Fecha_Salida
        ///      ,Fecha_Regreso
        ///      ,Descripcion
        ///      ,Peso
        ///      ,EmpleadoID
        ///      ,ClienteID
        ///      ,PrioridadID
        ///      ,Borrado
        ///) values 
        ///(
        ///      @Destino
        ///      ,@Fecha_Salida
        ///      ,@Fecha_Regreso
        ///      ,@Descripcion
        ///      ,@Peso
        ///      ,@EmpleadoID
        ///      ,@ClienteID
        ///      ,@PrioridadID
        ///      ,0
        ///).
        /// </summary>
        internal static string InsertarEntrega {
            get {
                return ResourceManager.GetString("InsertarEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Prioridad(
        ///  Nombre
        ///  ,horas
        ///  ,borrado)
        ///  values
        ///  (
        ///  @nombre
        ///  ,@horas
        ///  ,0
        ///  ).
        /// </summary>
        internal static string InsertarPrioridad {
            get {
                return ResourceManager.GetString("InsertarPrioridad", resourceCulture);
            }
        }
    }
}
